tlsSecret:
  name: ""
  tlsCrt: ""
  tlsKey: ""

image:
  repository:
  tag:
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 100Mi
nodeSelector: {}
tolerations: []
replicas: 1
service:
  ports:
  - name: api
    nodePort: 31210
    port: 443
    protocol: TCP
    targetPort: 8443
  type: NodePort
  targetGroupARN: ""
serviceInternal:
  ports:
    - name: metrics
      port: 9273
      targetPort: 0
    - name: profile
      port: 4269
      targetPort: 0
  type: ClusterIP
config:
  configJson: |-
    {
        "host": "0.0.0.0",
        "port": 8443,
        "log_level": "info",
        "json_log_enable": true,
        "namespace": "tesla_telemetry",
        "reliable_ack": false,
        "monitoring": {
            "prometheus_metrics_port": 9273,
            "profiler_port": 4269,
            "profiling_path": "/tmp/trace.out"
        },
        "rate_limit": {
            "enabled": true,
            "message_interval_time": 30,
            "message_limit": 1000
        },
        "records": {
            "alerts": [
                "logger"
            ],
            "errors": [
                "logger"
            ],
            "V": [
                "logger"
            ]
        },
        "use_default_eng_ca": true,
        "tls": {
            "server_cert": "/etc/tesla/certs/server/tls.crt",
            "server_key": "/etc/tesla/certs/server/tls.key"
        }
    }
kubernetesClusterDomain: cluster.local