{{- if .Values.tlsSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fleet-telemetry.fullname" . }}
  labels:
  {{- include "fleet-telemetry.labels" . | nindent 4 }}
data:
  tls.crt: {{ required "tlsSecret.tlsCrt is required"
    .Values.fleetStreamingApiEngVnCloudTeslaCom27H49M99Df.tlsCrt | b64enc | quote
    }}
  tls.key: {{ required "tlsSecret.tlsKey is required"
    .Values.fleetStreamingApiEngVnCloudTeslaCom27H49M99Df.tlsKey | b64enc | quote
    }}
type: kubernetes.io/tls
{{- end -}}
