apiVersion: v1
kind: Service
metadata:
  name: {{ include "fleet-telemetry.fullname" . }}-internal
  labels:
    prometheus_scrape: "true"
    role: api
    service: fleet-telemetry
  {{- include "fleet-telemetry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceInternal.type }}
  selector:
    role: api
    service: fleet-telemetry
  {{- include "fleet-telemetry.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.serviceInternal.ports | toYaml | nindent 2 -}}